version: "3.8"

services:
  # Service pour l'application HotelReservation
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hotel-reservation-container
    ports:
      - "8080:8080"  # Mapping du port
    environment:
      - SPRING_PROFILES_ACTIVE=prod  # Profil Spring actif
    volumes:
      - ./logs:/app/logs  # Volume pour conserver les logs
    networks:
      - monitoring-network

  # Service pour Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Fichier de configuration Prometheus
    ports:
      - "9090:9090"  # Port pour accéder à Prometheus
    networks:
      - monitoring-network

  # (Optionnel) Service pour Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"  # Port pour accéder à Grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin  # Nom d'utilisateur par défaut
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Mot de passe par défaut
    depends_on:
      - prometheus
    networks:
      - monitoring-network

networks:
  monitoring-network:
    driver: bridge