global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "hotel-reservation"
    metrics_path: "/actuator/prometheus"  # Chemin des métriques exposées par votre application
    scrape_interval: 5s
    static_configs:
      - targets: ["app:8080"]  # Le service "app" exposant les métriques